# Caminho do executável do navegador Google Chrome
GCHROME=
# Caminho para salvar arquivos baixados
DATAPATH=
# Nome de usuário a ser usado na autenticação
USUARIO=
# Senha do usuário usado na autenticação
PALAVRA=
# Possíveis nomes de coluna referente ao CONTRATO
COLUNAS_CONTRATO=
# Possíveis nomes de coluna referente ao CODIGO
COLUNAS_CODIGO=
# Possíveis nomes de coluna referente ao PEDIDO
COLUNAS_PEDIDO=
# Possíveis nomes de coluna referente ao MUNICIPIO
COLUNAS_MUNICIPIO=
# Possíveis nomes de coluna referente ao CONFORME
COLUNAS_CONFORME=
# Possíveis nomes de coluna referente ao VALORADO
COLUNAS_VALORADO=
# Configura emissão automática sem confirmação
EMITIR=
